# -*- coding: utf-8 -*-
"""CG

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjThFwOgLdRUP8jZpVhMdwHlo2KpQpHn
"""

import matplotlib.pyplot as plt


def main():
    print("----- Menu -----")
    choice = int(input(" 1: Point \n 2: Line Segment \n 3: Ray \n 4: Line \n"))
    if (choice == 1):
        print("----- Point -----")
        point()
 
    elif (choice == 2):
        print("----- Line Segment -----")
        lineSegment()

    elif (choice == 3):
        print("----- Ray -----")
        ray()

    elif (choice == 4):
        print("----- Line -----")
        line()
    else:
        raise Exception("Enter correct input")
    
def graph(x,y,title):
    plt.xlabel('x - axis')
    plt.ylabel('y - axis')
    plt.title(title)
    plt.grid()
    plt.plot(x, y, marker="o",  markeredgecolor="red", markerfacecolor="green")
    plt.show()


def point():
    a = input("Enter value of x and y coordinates: ")
    P1 = a.split(",")
    x_axis = float(P1[0])
    y_axis = float(P1[1])

    print("The point is : ", P1)
    
    graph(x_axis, y_axis, 'User given point')

def lineSegment():
    a = input("Enter value of x and y coordinates: ")
    P1 = a.split(",")
    x1 = float(P1[0])
    y1 = float(P1[1])

    b = input("Enter value of x and y coordinates: ")
    P2 = b.split(",")
    x2 = float(P2[0])
    y2 = float(P2[1])

    c1 = [x1, x2]
    c2 = [y1, y2]

    graph(c1, c2, 'Line Segment')

def ray():
    a = input("Enter value of x and y coordinates for first point: ")
    P1 = a.split(",")
    x1 = float(P1[0])
    y1 = float(P1[1])

    b = input("Enter value of x and y coordinates for second point: ")
    P2 = b.split(",")
    x2 = float(P2[0])
    y2 = float(P2[1])

    start = [x1, x2]
    end = [y1, y2]

    print("The first point is : ", P1)
    print("The second point is : ", P2)
    

    slope = (y2-y1)/(x2-x1)

    plt.xlabel('x - axis')
    plt.ylabel('y - axis')
    plt.title('Ray')
    plt.grid()
    plt.plot(start, end, marker="o",  markeredgecolor="red", markerfacecolor="green")
    ax = plt.axes()
    ax.arrow(x2, y2, slope, slope, head_width=0.05, head_length=0.05 )
    plt.show()

def line():
    a = input("Enter value of x and y coordinates for first point: ")
    P1 = a.split(",")
    x1 = float(P1[0])
    y1 = float(P1[1])

    b = input("Enter value of x and y coordinates for second point: ")
    P2 = b.split(",")
    x2 = float(P2[0])
    y2 = float(P2[1])

    start = [x1, x2]
    end = [y1, y2]

    infinity1 = [x1-5,x2+5]
    infinity2 = [y1-5,y2+5]

    print("The first point is : ", P1)
    print("The second point is : ", P2)

    fig, ax = plt.subplots()
    ax.scatter(start, end)
    label = ["P1", "P2"]

    for i, txt in enumerate(label):
        ax.annotate(txt, (start[i], end[i]))

    plt.xlabel('x - axis')
    plt.ylabel('y - axis')
    plt.title('Line')
    plt.grid()
    
    ax.plot(infinity1, infinity2)
main()

import matplotlib.pyplot as plt
def point():
    a = input("Enter value of x and y coordinates: ")
    P1 = a.split(",")
    x_axis = float(P1[0])
    y_axis = float(P1[1])

    print("The point is : ", P1)
    
    plt.xlabel('x - axis')
    plt.ylabel('y - axis')
    plt.title('User given point')
    plt.grid()
    plt.plot(x_axis, y_axis, marker="o",  markeredgecolor="red", markerfacecolor="green")
    plt.show()

point()

import matplotlib.pyplot as plt
def lineSegment():
    a = input("Enter value of x and y coordinates: ")
    P1 = a.split(",")
    x1 = float(P1[0])
    y1 = float(P1[1])

    b = input("Enter value of x and y coordinates: ")
    P2 = b.split(",")
    x2 = float(P2[0])
    y2 = float(P2[1])

    c1 = [x1, x2]
    c2 = [y1, y2]

    plt.xlabel('x - axis')
    plt.ylabel('y - axis')
    plt.title('Line Segment')
    plt.grid()
    plt.plot(c1, c2, marker="o",  markeredgecolor="red", markerfacecolor="green")
    plt.show()

lineSegment()

import matplotlib.pyplot as plt
def ray():
    a = input("Enter value of x and y coordinates for first point: ")
    P1 = a.split(",")
    x1 = float(P1[0])
    y1 = float(P1[1])

    b = input("Enter value of x and y coordinates for second point: ")
    P2 = b.split(",")
    x2 = float(P2[0])
    y2 = float(P2[1])

    start = [x1, x2]
    end = [y1, y2]

    print("The first point is : ", P1)
    print("The second point is : ", P2)
    

    slope = (y2-y1)/(x2-x1)

    plt.xlabel('x - axis')
    plt.ylabel('y - axis')
    plt.title('Ray')
    plt.grid()
    plt.plot(start, end, marker="o",  markeredgecolor="red", markerfacecolor="green")
    ax = plt.axes()
    ax.arrow(x2, y2, slope, slope, head_width=0.05, head_length=0.05 )
    plt.show()

ray()

import matplotlib.pyplot as plt
def line():
    a = input("Enter value of x and y coordinates for first point: ")
    P1 = a.split(",")
    x1 = float(P1[0])
    y1 = float(P1[1])

    b = input("Enter value of x and y coordinates for second point: ")
    P2 = b.split(",")
    x2 = float(P2[0])
    y2 = float(P2[1])

    start = [x1, x2]
    end = [y1, y2]

    infinity1 = [x1-5,x2+5]
    infinity2 = [y1-5,y2+5]

    print("The first point is : ", P1)
    print("The second point is : ", P2)

    fig, ax = plt.subplots()
    ax.scatter(start, end)
    label = ["P1", "P2"]

    for i, txt in enumerate(label):
        ax.annotate(txt, (start[i], end[i]))

    plt.xlabel('x - axis')
    plt.ylabel('y - axis')
    plt.title('Line')
    plt.grid()
    
    ax.plot(infinity1, infinity2)
line()